### ISSUE TITLE
Lost Audio after 10.9.2 update.

### ISSUE THREAD

**Issue by giacomoleopardo** [Piker-Alpha/AppleHDA8Series.sh#1]
It's not a big deal. As always done in the past, in less than 2 minutes I created a new AppleHDA892.kext. But I thought this kext would survive to system update! Did I miss anything? Or maybe not all updates work in the same way.
Zotac Z77 ITX
Intel 3770T
Mavericks 10.9.2
Chameleon v.2377

./AppleHDA8Series.sh -b AppleHDA -b AppleHDAController
layout id 3

**Comment by Piker-Alpha** [comment]
Closing old issues.
