### ISSUE TITLE
Output names became Russian

### ISSUE THREAD

**Issue by Rene1957** [Piker-Alpha/AppleHDA8Series.sh#10]
Hi Pike,
Thanks for your awesome work you're doing.
One thing that I found is that after DP3 or 4, the Output names for sound are being showed in Russian.
There is a folder created in AppleHDA>Contents>Resources>ru.lproj
After deleting it, the names are showed in English again. But after an update the ru.lproj folder is back again. I'm using V3.1 script.

Again, thanks for sharing your work.

![screen shot 2014-09-22 at 15 41 33](https://cloud.githubusercontent.com/assets/7432387/4357188/40196590-4260-11e4-917b-2e697049d4f3.png)

**Comment by Piker-Alpha** [comment]
Closing old issues.
