### ISSUE TITLE
VIA VT1828S / VT2020 ?

### ISSUE THREAD

**Issue by martell** [Piker-Alpha/AppleHDA8Series.sh#12]
I seen on your blog someone asked about this chipset.
Is this in anyway supported or easily added?

Codec: VIA VT1828S
CodecID: 285 623 361

If you need me to do anything like get info from the device i can as i have one 

Kind Regards
Martell

**Comment by Piker-Alpha** [comment]
Sorry. I have no intention to add support for chipsets other than Intel.
