### ISSUE TITLE
Does not load when using Clover kext injection

### ISSUE THREAD

**Issue by alphanull** [Piker-Alpha/AppleHDA8Series.sh#13]
First of all, I really like your solution, bc in conjunction with a Clover kext patch it allows for a completely untouched AppleHDA.kext. However, it seems the kext still needs to be placed in S/L/E.

When I put this kext in /EFI/CLOVER/kexts/10.10 it does not seem to load.

Question: is this a bug, a missing feature or more a kind of technical limitation? Of course it would be really nice if that would be possible, bc then you can have a completely untouched vanilla OS X installation, with everything hackintosh specific completely contained in your EFI partition. Right now, your patched kext is the only one which does not allow this, so of course it would be great if this could be made possible.

Otherwise, thanks and keep up the good work!

**Comment by theracermaster** [comment]
What Clover kext patch are you using with this script?

**Comment by Piker-Alpha** [comment]
Closing old issues (without a response for a while).
