### ISSUE TITLE
space in script path causes errors

### ISSUE THREAD

**Issue by khtang** [Piker-Alpha/AppleHDA8Series.sh#15]
If there is any space in the script path, patching fails and ambiguous redirect errors happen as the plist gets generated. Removing spaces in the parent directories solves the problem. 

The errors:
```
Creating symbolic link to AppleHDA ...
./AppleHDA8Series.sh: line 1263: $gInfoPlist: ambiguous redirect
./AppleHDA8Series.sh: line 1264: $gInfoPlist: ambiguous redirect
...(snipped)...
./AppleHDA8Series.sh: line 1317: $gInfoPlist: ambiguous redirect
Done.
```
Thank you.

**Comment by Piker-Alpha** [comment]
Thank you for reporting this. Will be fixed in v3.2
