### ISSUE TITLE
Please help. No sound on GA-X99M ALC1150

### ISSUE THREAD

**Issue by vladimirilm** [Piker-Alpha/AppleHDA8Series.sh#16]
1. OS X version/motherboard model/BIOS version/processor/graphics
	2. Procedure/Guide Used/AppleHDA.kext version
	3. AppleHDA(codec).kext (i.e., AppleHDA1150.kext)
	4. Copy of IOReg - IOReg_v2.1/File/Save a Copy As…, verify file (not
           ioreg.txt)
	5. Extra/dsdt.aml (if installed)
	6. Console/All Messages/kernel Sound assertions selected/Save
           Selection As…..
	7. Screenshot of System Information/Hardware/Audio/Intel High
           Definition Audio (not Devices)

 1) 10.10.3 / Gigabyte GA-X99M-Gaming 5 / BIOS version f4a / i7 5930K / PNY Nvidia GTX980
 2) tried with 
http://www.tonymacx86.com/yosemite-desktop-guides/143849-haswell-e-x99-motherboard-temporary-guide-os-x-10-10-a-23.html#post909616 (SSDT-1.aml taken from)
audio_cloverALC-100.command.zip 
last one https://github.com/toleda/audio_pikeralphaALC

 AppleHDA version 272.18
 3) included
 4) Mac Pro included
 5) SSDT-1.aml included
 6) sound assertion messages.log included
 7) screen shot included

**Comment by vladimirilm** [comment]
https://yadi.sk/d/5svoy7SegfTNs

**Comment by vladimirilm** [comment]
one more think - it looks like ports configured properly because if i insert earphones in green port on case - port description changed from "Internal speaker" to "Headphones"

**Comment by Piker-Alpha** [comment]
Closing old issues (issues are meant to address problems with the script. Not with the XML data and installation itself).
