### ISSUE TITLE
Version 3.1 Error on El Capitan

### ISSUE THREAD

**Issue by hoyanf** [Piker-Alpha/AppleHDA8Series.sh#19]
Encountered error when running the script

./AppleHDA8Series.sh: line 270: syntax error near unexpected token `('
./AppleHDA8Series.sh: line 270: `  printf "AppleHDA8Series.sh v${gScriptVersion} Copyright (c) 2013-$(date "+%Y") by Pike R. Alpha\n"'

**Comment by Piker-Alpha** [comment]
You seem to be the only person to run into this, so please re-download the script and try again..
