### ISSUE TITLE
Sleep Fix

### ISSUE THREAD

**Issue by wastez** [Piker-Alpha/AppleHDA8Series.sh#2]
Hello,

After sleep there is no sound output anymore.
Normaly i used an EAPD fix for such things on other devices (CodecCommander.kext, EAPDFix.kex) but it seems they are not working if AppleHDA ist not loaded directly.
So would it be possible to implement the EAPD fix directly into your loader?

**Comment by Piker-Alpha** [comment]
Sorry. I am about to close this issue. I have no time for it, but perhaps someone else wants to do this.

**Comment by wastez** [comment]
No Problem found a fix a Long Time ago.
