### ISSUE TITLE
AppleHDA1150 kext won't load because it's not signed for Yosemite beta2

### ISSUE THREAD

**Issue by vanhp** [Piker-Alpha/AppleHDA8Series.sh#9]
I have Realtek ALC 1150 that come with my mother board ASRock Z97 extreme6,
I'm running Yosemite public beta 2
I've tried the 2 method Piker-Alpha AppleHDA8series
 
1. the script complaining that the kext-dev-mode=1 is not set event though I put it in the boot argument.
2. The AppleHDA1150 kext was installed into S/L/E but it never loaded may be because it never signed. Boot with either kext-dev-mode=1 set or not have no effect.
3. My monitor is connected to ASUS R9 270 graphic card via HDMI and there is no sound from it

**Comment by Piker-Alpha** [comment]
Right. The kext is not signed, and never will be signed, so you have to use rootless=0 and a proper boot loader with SIP support by the time rootless was taken out.
